version: '3'

services:
  camunda:
    container_name: camunda
    image: pienta/camunda-project:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9990:9990"
    restart: unless-stopped
